site_name: Quantus Network Docs
site_description: Documentation for Quantus Network
theme:
  name: cinder
  custom_dir: 'cinder'
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - Governance:
    - Overview: governance.md
    - Governance Paths:
      - Path 0: governance/path_0.md
      - Path 1: governance/path_1.md
      - Path 2: governance/path_2.md
      - Path 3: governance/path_3.md
      - Path 4: governance/path_4.md
      - Path 5: governance/path_5.md
      - Tech Path 0: governance/tech_path_0.md
    - Vesting Scenarios: governance/vesting_scenarios.md 